### ISSUE TITLE
How do you disable looping?

### ISSUE THREAD

**Issue by tsordillo** [Creatide/AnimateMate#11]
I tried unchecking the 'Enable Loop' box when exporting my animation, but it still loops forever. Is there another way to make the gif loop only once? Thanks!

**Comment by niittymaa** [comment]
Great, this was good point! Remember that OS X own Preview loops animation always (I guess). 
I just added functionality to set loopcount in export to GIF animations. Just grab newest version and you can set loop count (0 = infinite). Just info if it's broken. I tested it and it works fine.
