### ISSUE TITLE
GIF quality settings? (i.e. dithering for shadows)

### ISSUE THREAD

**Issue by sogen** [Creatide/AnimateMate#2]
Hi, great plugin, congrats!
Trying to export a menu, but its shadow won't export well 
(the GIF shows a solid shadow instead of a smooth dithered one)
Is there a way to set dithering export for GIFs?

Thanks

**Comment by niittymaa** [comment]
In current version it's not possible to adjust GIF export dithering level. I added this to improvement list to get more control to GIF exporting options. At this stage I recommend to use export PNG sequence and use e.g. Photoshop to GIF conversion to get more options. [Here is video where I use that method in Photoshop.](https://goo.gl/ypVnCn)

**Comment by sogen** [comment]
Thanks!
