### ISSUE TITLE
Exporting to .GIF

### ISSUE THREAD

**Issue by J1mNasium** [Creatide/AnimateMate#20]
Thank you creating and sharing this plugin. I'm new to Sketch and I'm trying to create a simple animation for a research project but I'm unable to export the file to .gif. However, when I export .png I can see all the images so I'm doing something right, but .gif won't work. This happens regardless of how small/simple my animation is. I'm running the trial version of Sketch on Sierra, for what it's worth. Any help would be much appreciated.

**Comment by niittymaa** [comment]
Thanks you for letting me know this! I haven't installed Sierra yet. So I do not know if it's because of Sierra or something else. I'll install Sierra soon and test it out.

**Comment by niittymaa** [comment]
Yep, I can confirm that GIF exporting doesn't work with new macOS Sierra and sketch. I tested out sketch with sketch version 3.7-40.  PNG image sequence works properly.

At the moment I'm not sure where's the problem. Conversion process uses sips terminal commands. Is it because sketch or sierra, don't know yet.

**Comment by KarlFitz** [comment]
Gif exporting working for me in Sketch 40.1 with El Capitan 10.11.3

**Comment by niittymaa** [comment]
Ok, now updated command a little bit and it seems to work again for me with Sierra and Sketch 40.1. Problem was in terminal command where using sips conversion. It doesn't save converted gif images anymore for some reason. I'm not so familiar with that terminal black magic.

Please report if you get problem again.

**Comment by golinmarq** [comment]
I have this problem

**Comment by egoens** [comment]
I have this same problem. Running Sketch 44 on Sierra.
