### ISSUE TITLE
gifsicle Process  does not finish in Sketch 42

### ISSUE THREAD

**Issue by defrian** [Creatide/AnimateMate#24]
I am using Sketch 42. With the latest version of AnimateMate I can export but the gifsicle Prozess consumes 100% CPU und does not finish. When I force quit it it is gets restarted over and over.

I am Using Sketch 42 on macOS 10.12.3

**Comment by niittymaa** [comment]
I think this sounds that it just still creating GIF. Creating gif uing gifsicle is quite slow process and there is no actual indicator about converting process. So it could be same as https://github.com/Creatide/AnimateMate/issues/14

Best way to test out if gif export works is, export small and only couple frames length animation and it should export it fast.
