### ISSUE TITLE
Sketch 42 and 44, Crash on Export, recreating files as they are removed

### ISSUE THREAD

**Issue by Lucas-gronlund** [Creatide/AnimateMate#28]
As the title suggest, AnimateMate is doing some really weird stuff right now. As you export, Sketch crashes but creates the animation. Sometimes they don't work either. After that, you cannot delete the gif, it recreates itself every minute taking up loads of space on my drive. Until i restart my Mac.

Also thanks for creating AnimateMate, it's the only plugin I use for Sketch, it's so amazing!

**Comment by Lucas-gronlund** [comment]
After further testing, the freeze goes away after some seconds as long as I don't add a mask to the artboard

**Comment by niittymaa** [comment]
If you do not wait until process is complete it will create file again ang again. All that happens inside SIP command in terminal. It uses gifsicle library for gif converting process. So that explains why it creates again if you delete file before complete. So with big image size or animation size, exporting gif is not recommended. It could take too much time.

But that sounds very wierd if it doesn't stop until the restart! Never happened for me yet.
I have just tested out plugin with Sketch 44.1 and Sierra OS, but everything seems to work fine for me while exporting. If you share some example file I could also test if that makes same for me...

**Comment by nakele** [comment]
@Lucas-gronlund I have 44.1 on El Capitan, creating a GIF will take some time but for me if I let it be eventually it works fine.

Perhaps you could send a Sketch sample file to export to gif so that I can try on my machine

**Comment by Lucas-gronlund** [comment]
[BrokenAnimation.zip](https://github.com/Creatide/AnimateMate/files/1029050/BrokenAnimation.zip)

Here is an example, note that the text jumped down to bottom right corner after the crash as well

**Comment by nakele** [comment]
Hi @Lucas-gronlund, I've reanimated the text, I'm assuming that the text should just pan from left to right. This is the result after a whole minute waiting and do wait, just don't do anythingelse after you export and just wait to be done: 
![apple tv_0-50](https://cloud.githubusercontent.com/assets/12185661/26452919/bd69f546-4159-11e7-887e-969c9b0c3a7f.gif)

The poor colour gradation is a GIF limitation, nothing to do with this plugin, no way to solve it, it's just a limitation of how GIF works.

In regards to the text end up in the wrong position after export it's an issue I notice as well when you animate something in a group, have a look at this thread: https://github.com/Creatide/AnimateMate/issues/27

In any case I believe it's solved, if you re-download the plugin now it should be fixed. Make sure U use Sketch version >= 44.1

**Comment by Lucas-gronlund** [comment]
Thanks @nakele I actually got it to work now, the infinite crash still persists but now the result is as expected 👍  Really appreciate the help, thank you!

**Comment by niittymaa** [comment]
@Lucas-gronlund you can avoid that stupid jumping problem with just adding "empty" artboard sized rectangle, so now it thought that group is starting from top left corner. 

<img width="208" alt="image copied on 2017-05-25 at 19 13 pm" src="https://cloud.githubusercontent.com/assets/4587998/26459168/422b4338-417e-11e7-82d3-866d2be867d1.png">

Here is example.

![apple tv_0-50](https://cloud.githubusercontent.com/assets/4587998/26459128/21e6802e-417e-11e7-9a3b-c34e5df5ba5d.gif)
[BrokenAnimation.sketch.zip](https://github.com/Creatide/AnimateMate/files/1029577/BrokenAnimation.sketch.zip)
