### ISSUE TITLE
Ease visualiziation

### ISSUE THREAD

**Issue by iAlborz** [Creatide/AnimateMate#7]
![usldm](https://cloud.githubusercontent.com/assets/4399410/14089679/e763b344-f4ea-11e5-907a-8c9abc554160.png)

A visual way of selecting the ease would be much quicker. Right now the drop down is rather hard to use. a larger window with more options visible would be much easier to use.

**Comment by niittymaa** [comment]
This is good idea. The whole UI need to re-made for better usability and this is great idea for that.
